"""add reputation and intelligence schema

Revision ID: a9b8c7d6e5f4
Revises: e3c11fbeb6ab
Create Date: 2025-08-18 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a9b8c7d6e5f4'
down_revision = 'e3c11fbeb6ab'
branch_labels = None
depends_on = None


def def upgrade() -> None:
    # ### commands auto-generated by Alembic - please adjust! ###
    op.create_table('laces_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=18, scale=8), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('transaction_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('monitors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('site_name', sa.String(length=100), nullable=False),
    sa.Column('product_sku', sa.String(length=100), nullable=True),
    sa.Column('size_preference', sa.String(length=20), nullable=True),
    sa.Column('max_price', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('location_filter', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('success_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('intelligence_posts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('post_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('location_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('verification_count', sa.Integer(), nullable=True),
    sa.Column('laces_earned', sa.DECIMAL(precision=18, scale=8), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('reputation_score', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('laces_balance', sa.DECIMAL(precision=18, scale=8), nullable=True))
    op.add_column('users', sa.Column('tier', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('last_active_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('users', 'user_id', new_column_name='id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto-generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_active_at')
    op.drop_column('users', 'tier')
    op.drop_column('users', 'laces_balance')
    op.drop_column('users', 'reputation_score')
    op.alter_column('users', 'id', new_column_name='user_id')
    op.drop_table('intelligence_posts')
    op.drop_table('monitors')
    op.drop_table('laces_transactions')
    # ### end Alembic commands ###
