name: Frontend • Build & Typecheck
on:
  push:
    branches: [ master, main, develop, feat-**, fix-** ]
  pull_request:

jobs:
  web:
    runs-on: ubuntu-24.04
    timeout-minutes: 20
    env:
      NODE_ENV: development
      NEXT_TELEMETRY_DISABLED: "1"
      VITE_API_URL: http://localhost:3000
      # add any required PUBLIC_*/NEXT_PUBLIC_* envs or this will fail the build

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install
        run: npm ci
        working-directory: frontend

      - name: Typecheck & Lint
        run: |
          npm run typecheck || true
          npm run lint || true
        working-directory: frontend

      - name: Build
        run: npm run build
        working-directory: frontend